name: flutter_audio_output
description: A Flutter package flutter_audio_output is to adapt music output.
version: 0.0.4
homepage: https://github.com/LondonX/flutter_audio_output.git

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.itsmurphy.flutter_audio_output
        pluginClass: FlutterAudioOutputPlugin
      ios:
        pluginClass: FlutterAudioOutputPlugin
